# Generated by Django 4.2.4 on 2023-08-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillSummaryGemInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemInvoiceNo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BillSummaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gemInvoiceNos', models.ManyToManyField(related_name='billSummaryDatas', to='api.billsummarygeminvoice')),
            ],
        ),
        migrations.CreateModel(
            name='BillSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('iat', models.CharField(max_length=20)),
                ('sub', models.CharField(max_length=20)),
                ('aud', models.CharField(max_length=20)),
                ('iss', models.CharField(max_length=20)),
                ('data', models.ManyToManyField(related_name='billSummaries', to='api.billsummarydata')),
            ],
        ),
    ]
