# Generated by Django 4.2.4 on 2023-08-18 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='aud',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='iat',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='iss',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='status',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='billsummary',
            name='aud',
        ),
        migrations.RemoveField(
            model_name='billsummary',
            name='iat',
        ),
        migrations.RemoveField(
            model_name='billsummary',
            name='iss',
        ),
        migrations.RemoveField(
            model_name='billsummary',
            name='status',
        ),
        migrations.RemoveField(
            model_name='billsummary',
            name='sub',
        ),
    ]
