# Generated by Django 4.2.4 on 2023-08-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billconsignee',
            name='consigneeAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billconsignee',
            name='consigneeDistrict',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billconsignee',
            name='consigneePin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
