# Generated by Django 4.2.4 on 2023-08-27 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billdetails',
            old_name='bill_amount',
            new_name='billAmount',
        ),
    ]
