# Generated by Django 4.2.4 on 2023-08-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_billorder_buyergstn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billorder',
            name='buyerGstn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billorder',
            name='deductions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billorder',
            name='vendorGstStatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billorder',
            name='vendorGstn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
